routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\RazorpayController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SocialLinkController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Front Routes
Route::get('/', [FrontController::class, 'index'])->name('front');
Route::get('/detail/{slug}', [FrontController::class, 'productDetail']);
Route::get('faq', [FrontController::class, 'faq'])->name('faq');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('shopping-cart', [FrontController::class, 'cart'])->name('cart');
Route::get('sign-in', [FrontController::class, 'signIn'])->name('sign-in');
Route::get('sign-up', [FrontController::class, 'signUp'])->name('sign-up');
Route::get('forgot-password', [FrontController::class, 'forgotPassword'])->name('forgot-password');
Route::get('reset-password', [FrontController::class, 'resetPassword'])->name('reset-password');

Auth::routes();

Route::get('/home', function () {
    return view('dashboard.dashboard.dashboard');
});
Route::resource('users', UserController::class);
Route::resource('coupons', CouponController::class);

Route::get('/orders', function () {
    return view('dashboard.orders.orders');
});
Route::get('/create_orders', function () {
    return view('dashboard.orders.create');
});
Route::get('/invoices', function () {
    return view('dashboard.invoices.index');
});
Route::get('/add_address', function () {
    return view('dashboard.settings.add_addresses');
});
Route::get('/add_languages', function () {
    return view('dashboard.settings.add_languages');
});
Route::get('/language-settings', function () {
    return view('dashboard.settings.language-settings.index');
});
Route::get('/smtp-settings', function () {
    return view('dashboard.settings.smtp-settings.create');
});
Route::get('/sms-settings', function () {
    return view('dashboard.settings.sms-settings.create');
});
Route::get('/addresses', function () {
    return view('dashboard.settings.addresses.index');
});
Route::get('/payments', function () {
    return view('dashboard.settings.payment-gateway-settings.create');
});
Route::get('settings', [SettingController::class, 'index'])->name('setting');
Route::resource('categories', CategoryController::class);
Route::get('get-sub-categories/{categoryId}', [SubCategoryController::class, 'getSubcategories'])->name('get_sub_categories');
Route::resource('sub-categories', SubCategoryController::class);
Route::resource('products', ProductController::class);
Route::resource('users', UserController::class);
Route::resource('general-settings', GeneralSettingController::class);
Route::resource('languages', LanguageSettingController::class);
Route::resource('social-links', SocialLinkController::class);
Route::resource('faqs', FaqController::class);

/* Payment Gateways */
// Stripe Payment
Route::get('/stripe-payment', [StripeController::class, 'handleGet']);
Route::post('/stripe-payment', [StripeController::class, 'handlePost'])->name('stripe.payment');
// Razorpay Payment
Route::get('razorpay-payment', [RazorpayController::class, 'index']);
Route::post('razorpay-payment', [RazorpayController::class, 'store'])->name('razorpay.payment.store');
Route::get('/index', [FrontController::class, 'index']);

app/Models/Product.php
<?php

namespace App\Models;

use App\Observers\ProductsObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected static function boot()
    {
        parent::boot();
        static::observe(ProductsObserver::class);
    }


    protected $fillable = [
        'name',
        'price',
        'descriptions',
        'photo',
        'quantity',
        'status',
        'created_by',
        'updated_by',
    ];

    // Accessor
    public function getProductPhotoAttribute()
    {
        $defaultPath = asset('products-uploads/defualt/not found.png');

        $path = asset('products-uploads/products/' . $this->photo);

        return $this->photo == '' ? $defaultPath : $path;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\StoreProduct;
use App\Http\Requests\Product\UpdateProduct;
use App\Models\Category;
use App\Models\Product;
use App\Models\SubCategory;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::get();
        return view('dashboard.products.index', compact('products'));
        // return $products = Product::get()->toJson();
    }

    public function create()
    {
        $categories = Category::get();
        $subCategories = SubCategory::get();

        return view('dashboard.products.create', compact('categories', 'subCategories'));
    }

    public function store(StoreProduct $request)
    {
        $products = new Product;
        $products->category_id = $request->category_id;
        $products->sub_category_id = $request->sub_category_id;
        $products->name = $request->name;
        $products->price = $request->price;
        $products->quantity = $request->quantity;
        $products->featured = $request->featured;
        $products->description = $request->description;
        $products->status = $request->status;
        $products->save();

        // if ($request->hasfile('File')) {
        //     foreach ($request->file('File') as $file) {
        //         $name = $file->getClientOriginalName();
        //         $file->move(public_path() . '/uploads/', $name);
        //         $imgData[] = $name;
        //     }
        // }
        return redirect('products')->with(['success' => 'Product added.']);
    }

    public function show($id)
    {
        $products = Product::find($id);
        $categories = Category::get();
        $subCategories = SubCategory::get();

        return view('dashboard.products.show', compact('products', 'categories', 'subCategories'));
    }

    public function edit($id)
    {
        $products = Product::find($id);
        $categories = Category::get();
        $subCategories = SubCategory::get();

        return view('dashboard.products.edit', compact('products', 'categories', 'subCategories'));
    }

    public function update(UpdateProduct $request, $id)
    {
        $products = Product::find($id);
        $products->name = $request->name;
        $products->price = $request->price;
        $products->quantity = $request->quantity;
        $products->featured = $request->featured;
        $products->description = $request->description;
        $products->status = $request->status;
        $products->save();

        return redirect('/products')->with(['success' => 'Product has been updated.']);
    }

    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect('/products')->with(['success' => 'Product has been deleted.']);
    }
}

resources/views/dashboard/products/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Add Product
@endsection

@section('css')

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone.min.css" integrity="sha512-jU/7UFiaW5UBGODEopEqnbIAHOI8fO6T99m7Tsmqs2gkdujByJfkCbbfPSN4Wlqlb9TGnsuC0YgUgWkRBK7B9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{{ asset('asset/css/plugins/summernote/summernote.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/css/plugins/summernote/summernote-bs3.css') }}" rel="stylesheet">

    <link href="{{ asset('asset/css/plugins/dropzone/basic.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/css/plugins/dropzone/dropzone.css') }}" rel="stylesheet">
@endsection
@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Add Products</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/home">Home</a>
                </li>

                <li>
                    <a href="{{ route('products.index') }}">Products</a>
                </li>
                <li class="active">
                    <strong>Add Product</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('products.index') }}" class="btn btn-warning mt-3" id="save-data">
                <span class="fa fa-arrow-left"></span>
                Back
            </a>
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save</button>
        </div>

    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('products.store') }}"  id="image-upload" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Product Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group @error('category_id') has-error @enderror">
                                        <label for="category_id">Category <span class="text-danger">*</span></label>
                                        <select class="form-control" name="category_id" id="category_id">
                                            <option>Select</option>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="category_id">Sub-Category </label>
                                        <select class="form-control" name="sub_category_id" id="sub_category_id">
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('product_name') has-error @enderror">
                                        <label for="product_name">Product Name <span class="text-danger">*</span></label>
                                        <input type="text" placeholder="Enter product_name" class="form-control" name="name"
                                            id="product_name" value="{{ old('product_name') }}">
                                        @error('product_name')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('price') has-error @enderror">
                                        <label for="price">Price <span class="text-danger">*</span></label>
                                        <input type="price" class="form-control" placeholder="Enter price" name="price"
                                            id="price" value="{{ old('price') }}">
                                        @error('price')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('discount') has-error @enderror">
                                        <label for="discount">Discount </label>
                                        <input type="number" class="form-control" placeholder="Enter discount in %" name="discount"
                                            id="discount" value="{{ old('discount') }}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('quantity') has-error @enderror">
                                        <label for="quantity">Quantity <span class="text-danger">*</span></label>
                                        <input type="number" class="form-control" placeholder="Enter quantity"
                                            name="quantity" id="quantity" value="{{ old('quantity') }}">
                                        @error('quantity')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-12 mt-2">
                                    <div class="form-group @error('featured') has-error @enderror">
                                        <label for="featured">Featured</label>
                                        <div class="enable ">
                                            <input type="hidden" value="0" id="checkBox1" name="featured" class="js-switch_3" />
                                            <input type="checkbox" value="1" id="checkBox" name="featured" class="js-switch_3" />
                                        </div>
                                     </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('description') has-error @enderror">
                                        <label for="description">Description <span class="text-danger">*</span></label>
                                        <textarea class="form-control summernote" name="description" id="description">
                                        </textarea>
                                        @error('description')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('status') has-error @enderror">
                                        <label for="status">Status <span class="text-danger">*</span></label>
                                        <select class="form-control" name="status" id="state">
                                            <option>Select</option>
                                            <option value="active">active</option>
                                            <option value="inactive">inactive</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="ibox float-e-margins">
                                        <div class="ibox-title">
                                            <h5>Multi Photo</h5>
                                        </div>
                                        <div class="ibox-content">
                                            <input type="file" name="file" multiple="" data-default-file=/>
                                        </div>
                                    </div>
                                    <div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
            </form>
        </div>
    </div>

@endsection
@section('script')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js" integrity="sha512-VQQXLthlZQO00P+uEu4mJ4G4OAgqTtKG1hri56kQY1DtdLeIqhKUp9W/lllDDu3uN3SnUNawpW7lBda8+dSi7w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{{ asset('asset/js/plugins/switchery/switchery.js') }}"></script>

    <script src="{{ asset('js/dashboard.js') }}"></script>
    <script src="{{ asset('asset/js/jquery-2.1.1.js') }}"></script>
    <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('asset/js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
    <script src="{{ asset('asset/js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
         <!-- Custom and plugin javascript -->
    <script src="{{ asset('js/inspinia.js') }}"></script>
    <script src="{{ asset('js/plugins/pace/pace.min.js') }}"></script>
    <!-- SUMMERNOTE -->
    <script src="{{ asset('asset/js/plugins/summernote/summernote.min.js') }}"></script>
    <script>

        $(document).ready(function() {
        $('.summernote').summernote();

        });

        var edit = function() {
            $('.click2edit').summernote({
                focus: true
            });
        };
        var save = function() {
            var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
            $('.click2edit').destroy();
        };

        $(document).on('click', '#save-data', function() {
            $('form').submit();
        });

        $(document).on('change', '#category_id', function() {

            var categoryId = $(this).val();

            let url = "{{ route('get_sub_categories', ':id') }}";
            url = url.replace(':id', categoryId);

            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    $('#sub_category_id').html(response);
                }
            });

        });

    </script>

@endsection

resources/views/dashboard/products/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Products
@endsection

@section('css')
    <!-- DataTable -->
    <link href="{{ asset('asset/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">

@endsection

@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-11">
            <h2>Product</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/home">Home</a>
                </li>

                <li class="active">
                    <strong>Product</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-1">
            <a href="{{route ('products.create')}}" class="btn btn-primary mt-3">
                <span class="fa fa-plus"></span>
                Add</a>
        </div>
    </div>
@endsection
@section('content')

    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Product List
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover users-table">
                                <thead>
                                    <tr>
                                        <th>Photo</th>
                                        <th>Product Name</th>
                                        <th>Quantity</th>
                                        <th>Price</th>
                                        <th>Description</th>
                                        <th>Status</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($products as $product)

                                    <tr>
                                        <td>
                                            <img src="{{ $product->product_photo }}" alt="" height="80"
                                                width="150">
                                        </td>
                                        <td>
                                           {{ $product->name }}
                                        </td>
                                        <td>
                                            {{ $product->quantity }}

                                        </td>
                                        <td>
                                            {{ $product->price }}

                                        </td>
                                        <td>
                                            {{ $product->description }}
                                        </td>
                                        <td>
                                            @if ($product->status == 'active')
                                                <span class="label label-primary">Active</span>
                                            @else
                                                <span class="label label-danger">In-Active</span>
                                            @endif
                                        </td>

                                        <td class="text-right">
                                            <div class="btn-group">
                                                <a href="{{ route('products.show',$product->id) }}" class="btn-white btn btn-xs">View</a>

                                                <a href="{{ route('products.edit',$product->id) }}" class="btn-white btn btn-xs">Edit</a>

                                                <a href="javascript:;" data-product-id="{{ $product->id }}" class="btn-white btn btn-xs delete-product">Delete</a>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <!-- Mainly scripts -->
    <script src="{{ asset('js/dashboard.js') }}"></script>

    {{-- Datatable --}}
    <script src=" {{ asset('asset/js/plugins/dataTables/datatables.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('.users-table').DataTable();

            @if (session('success'))
                toastr.success('{{ session('success') }}', 'Success');
            @endif


            $('.delete-product').click(function() {

                let productId = $(this).data('product-id');

                // Generate Token method 1
                // let token = $("meta[name='csrf-token']").attr("content");

                // Generate Token method 2
                let token = '{{ csrf_token() }}';

                let url = '{{ route('products.destroy', ':id') }}';
                url = url.replace(':id', productId);

                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this data!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                }, function() {

                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {
                            "_token": token,
                            "_method": 'DELETE',
                        },
                        success: function() {
                            swal("Deleted!", "Product has been deleted.",
                                "success");
                            setTimeout(() => {
                                location.reload();
                            }, 3000);
                        }
                    });

                });
            });

        });
    </script>

@endsection