routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\RazorpayController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SocialLinkController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Front Routes
Route::get('/', [FrontController::class, 'index'])->name('front');
Route::get('/detail/{slug}', [FrontController::class, 'productDetail']);
Route::get('faq', [FrontController::class, 'faq'])->name('faq');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('shopping-cart', [FrontController::class, 'cart'])->name('cart');
Route::get('sign-in', [FrontController::class, 'signIn'])->name('sign-in');
Route::get('sign-up', [FrontController::class, 'signUp'])->name('sign-up');
Route::get('forgot-password', [FrontController::class, 'forgotPassword'])->name('forgot-password');
Route::get('reset-password', [FrontController::class, 'resetPassword'])->name('reset-password');

Auth::routes();

Route::get('/home', function () {
    return view('dashboard.dashboard.dashboard');
});
Route::resource('users', UserController::class);
Route::resource('coupons', CouponController::class);

Route::get('/orders', function () {
    return view('dashboard.orders.orders');
});
Route::get('/create_orders', function () {
    return view('dashboard.orders.create');
});
Route::get('/invoices', function () {
    return view('dashboard.invoices.index');
});
Route::get('/add_address', function () {
    return view('dashboard.settings.add_addresses');
});
Route::get('/add_languages', function () {
    return view('dashboard.settings.add_languages');
});
Route::get('/language-settings', function () {
    return view('dashboard.settings.language-settings.index');
});
Route::get('/smtp-settings', function () {
    return view('dashboard.settings.smtp-settings.create');
});
Route::get('/sms-settings', function () {
    return view('dashboard.settings.sms-settings.create');
});
Route::get('/addresses', function () {
    return view('dashboard.settings.addresses.index');
});
Route::get('/payments', function () {
    return view('dashboard.settings.payment-gateway-settings.create');
});
Route::get('settings', [SettingController::class, 'index'])->name('setting');
Route::resource('categories', CategoryController::class);
Route::get('get-sub-categories/{categoryId}', [SubCategoryController::class, 'getSubcategories'])->name('get_sub_categories');
Route::resource('sub-categories', SubCategoryController::class);
Route::resource('products', ProductController::class);
Route::resource('users', UserController::class);
Route::resource('general-settings', GeneralSettingController::class);
Route::resource('languages', LanguageSettingController::class);
Route::resource('social-links', SocialLinkController::class);
Route::resource('faqs', FaqController::class);

/* Payment Gateways */
// Stripe Payment
Route::get('/stripe-payment', [StripeController::class, 'handleGet']);
Route::post('/stripe-payment', [StripeController::class, 'handlePost'])->name('stripe.payment');
// Razorpay Payment
Route::get('razorpay-payment', [RazorpayController::class, 'index']);
Route::post('razorpay-payment', [RazorpayController::class, 'store'])->name('razorpay.payment.store');
Route::get('/index', [FrontController::class, 'index']);

app/Http/Controllers/LayoutController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\SubCategory;
use Illuminate\Http\Request;

class LayoutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::get();
        $subcategories = SubCategory::get();
        return view('front.home', compact('categories', 'subcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    {{-- Bootstrap --}}
    <link href="{{ asset('asset/css/bootstrap.min.css') }}" rel="stylesheet">


    {{-- Font Awesome --}}
    <link href="{{ asset('asset/font-awesome/css/font-awesome.css') }}" rel="stylesheet">

    {{-- Animate Css --}}
    <link href="{{ asset('css/dashboard.css') }}" rel="stylesheet">

    @yield('css')
</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                                <img alt="image" class="img-circle"
                                    src="{{ asset('asset/img/profile_small.jpg') }}" />
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear"> <span class="block m-t-xs"> <strong
                                            class="font-bold">Admin</strong>
                                    </span> <span class="text-muted text-xs block">Manager<b class="caret"></b></span>
                                </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="#">Profile</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    <li class="active">
                        <a href="/home"><i class="fa fa-th-large"></i> <span class="nav-label">
                            {{ __('lang.Dashboard') }}</span></a>
                    </li>
                    <li>
                        <a href="{{ route('users.index') }}"><i class="fa fa-users"></i> <span
                                class="nav-label">{{ __('lang.Users') }}</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">{{ __('lang.Manage Products') }}</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="{{ route('categories.index') }}">{{ __('lang.Category') }}</a></li>
                            <li><a href="{{ route('sub-categories.index') }}">{{ __('lang.Sub Category') }}</a></li>
                            <li><a href="{{ route('products.index') }}">{{ __('lang.Products') }}</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="/coupons"><i class="fa fa-money"></i> <span class="nav-label">{{ __('lang.Coupons') }}</span>
                        </a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-shopping-cart"></i> <span class="nav-label">{{ __('lang.Manage Orders') }}</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="/orders">{{ __('lang.Orders') }}</a></li>
                            <li><a href="/invoices">{{ __('lang.Invoices') }}</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-pie-chart"></i> <span class="nav-label">{{ __('lang.Reports') }}</span></a>
                    </li>
                    <li>
                        <a href="{{ route('setting') }}"><i class="fa fa-gears"></i> <span class="nav-label">{{ __('lang.Settings') }}</span></a>                    </li>
                </ul>

            </div>
        </nav>
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i
                                class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control"
                                    name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Welcome Admin</span>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i> <span class="label label-warning">0</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i> <span class="label label-primary">0</span>
                            </a>
                        </li>
                        <li>
                            <a href="login.html">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            @yield('breadcrum')
            @yield('content')
            <div class="footer">
                <div class="pull-right">
                    <strong>Free</strong>
                </div>
                <div>
                    <strong>Copyright</strong> marazzo &copy; 2021-2022
                </div>
            </div>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{{ asset('js/dashboard.js') }}"></script>

    <script>
        $(document).ready(function() {


            const modal = '#modal';
            const modal_heading = '#modelHeading';

            $('.users-table').DataTable();

            toastr.options = {
                "closeButton": true,
                "debug": false,
                "progressBar": true,
                "preventDuplicates": false,
                "positionClass": "toast-top-right",
                "onclick": null,
                "showDuration": "400",
                "hideDuration": "1000",
                "timeOut": "7000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
                }
        });
    </script>

    @yield('script')
</body>

</html>